version: "2.3"
services:
  xserver:
    image: jskrobotics/agent_system_xserver:2021
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80"
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  simulator:
    image: temp_webots:latest_xserver
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    command: [bash, -c, 'until xset q; do sleep 3; done && webots']
    #command: [bash, -c, 'while true; do sleep 5; done'] ##for debug
    #command: [ /entrypoint_xserver.sh, roslaunch, target_pkg, target.launch ]
    environment:
      - DISPLAY=:1
      # - DOCKER_ROS_SETUP=/catkin_ws/devel/setup.bash
      # - ROS_MASTER_URI=http://localhost:11311
      # - ROS_IP=localhost
      # - ROS_HOSTNAME=localhost
      # - ROS_HOME=/ros_home
    volumes_from:
      - xserver
    depends_on:
      - xserver
    volumes: [ '/jskrobotics:/jskrobotics' ]
