## before running: xhost +si:localuser:root
## after running: xhost -local:root
## docker-compose -p gazebo -f docker-compose-gazebo.yaml up
version: "2.3"
services:
  xserver:
    image: jskrobotics/agent_system:xserver_2021
    ipc: host
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:80" ## 3000 is port for http / open http://localhost:3000 with web browser
    environment:
      - DISPLAY=:1
    healthcheck:
      test: ["CMD-SHELL", "test -e /tmp/.X11-unix/X1"]
      interval: "1s"
      retries: 20
  main:
    image: jskrobotics/agent_system:gazebo11_dart_2021
    ipc: host
    network_mode: host
    security_opt:
      - seccomp:unconfined
    runtime: nvidia
    command: [bash, -c, 'until xset q; do sleep 3; done && vglrun gazebo']
    #command: [bash, -c, 'while true; do sleep 5; done'] ##for debug
    #command: [ /entrypoint_xserver.sh, roslaunch, target_pkg, target.launch ]
    environment:
      - DISPLAY=:1
      - VGL_DISPLAY=:0 ## naitive display (running opengl)
      - DOCKER_ROS_SETUP=/gazebo_ros_pkg_ws/install/setup.bash
      - DOCKER_ROS_IP=localhost
      # - ROS_MASTER_URI=http://localhost:11311
      # - ROS_IP=localhost
      # - ROS_HOSTNAME=localhost
      # - ROS_HOME=/ros_home
              ## mount directory /tmp/jskrobotics -> docker:/jsk_robotics
    volumes:  ## you can change /tmp/jskrobotics to your favorite directory
      - /tmp/.X11-unix/X0:/tmp/.X11-unix/X0
      - '/tmp/jskrobotics:/jskrobotics'
    volumes_from:
      - xserver
    depends_on:
      - xserver
